### ISSUE TITLE
Async routes error

### ISSUE THREAD

**Issue by EmmanuelBeziat** [ausir0726/nuxt-route-with-params#1]
Hi,

I wanted to try your little app, and after a yarn install I got this:

![](https://images.emmanuelbeziat.com/2017-03-26-uk3cl.jpg)

It seems like a webpack conflict…

**Comment by ausir0726** [comment]
In fact I don't have idea about this .
but when I check it , I find I have some CRLF and LF problem for this repo .
and I fix `eslint` for `nuxt.config.js` file ( that for airbnb config , not standard )

maybe you can help re git clone and run it . 

![route](https://cloud.githubusercontent.com/assets/7247064/24328701/45e952ba-1223-11e7-823f-b3836a64aff0.gif)

**Comment by ausir0726** [comment]
and you should try use yarn 

that so fast 😆

**Comment by EmmanuelBeziat** [comment]
I tried to remove then re-clone the repo, still the same error about `async routes()`. Tested on macOS and Widnows.

I don’t know what’s going on. I have the same problem on my own tests, so I think it has Something to do with Something I have — or not — installed.

Thanks for your answer anyway :)

**Comment by ausir0726** [comment]
maybe you can try npm cache clean ( yarn cacne clean ) or else ?

**Comment by EmmanuelBeziat** [comment]
Still Nothing. I  think this is more about webpack than yarn/npm itself.

I’ll look further tonight, thanks!

**Comment by ausir0726** [comment]
@EmmanuelBeziat  
today is working day  😄 
my colleague have same problem like you . I find way for problem .
this problem is async/await is es2017 , you need upgrade your node js >= 7.6
only >= 7.6 node.js support async/await 
because , `nuxt.config.js` not running in Babel complier .

**Comment by EmmanuelBeziat** [comment]
Awesome, thanks!
